name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest Flask-Testing pymongo

    # Step 4: Set up MongoDB for testing
    - name: Set up MongoDB
      run: |
        docker pull mongo:latest
        docker run -d -p 27017:27017 --name mongo mongo:latest
        sleep 15  # Wait for MongoDB to start

    # Step 5: Run tests
    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q tests/

    # Step 6: Clean up MongoDB container
    - name: Clean up MongoDB container
      run: |
        docker stop mongo
        docker rm mongo
