name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Set up MongoDB for testing
      - name: Set up MongoDB
        run: |
          docker pull mongo:latest
          docker run -d -p 27017:27017 --name mongo mongo:latest
          # Wait for MongoDB to be ready (use nc or a similar tool)
          sudo apt-get install -y netcat
          until nc -zv localhost 27017; do
            echo "Waiting for MongoDB to be ready..."
            sleep 1
          done
          echo "MongoDB is ready"

      # Step 5: Run tests with pytest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q tests/

      # Step 6: Clean up MongoDB container
      - name: Clean up MongoDB container
        run: |
          docker stop mongo
          docker rm mongo
name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Install pytest explicitly (in case it's not in requirements.txt)
      - name: Install pytest
        run: |
          pip install pytest

      # Step 5: Set up MongoDB for testing
      - name: Set up MongoDB
        run: |
          docker pull mongo:latest
          docker run -d -p 27017:27017 --name mongo mongo:latest
          # Wait for MongoDB to be ready (use nc or a similar tool)
          sudo apt-get install -y netcat
          until nc -zv localhost 27017; do
            echo "Waiting for MongoDB to be ready..."
            sleep 1
          done
          echo "MongoDB is ready"

      # Step 6: Run tests with pytest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q tests/

      # Step 7: Clean up MongoDB container
      - name: Clean up MongoDB container
        run: |
          docker stop mongo
          docker rm mongo
