name: Deploy Application

# Triggers this action when you push code to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu virtual machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step to use the secrets securely
    - name: Set Environment Variables
      env:
        MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      run: |
        echo "MongoDB Username: $MONGODB_USERNAME"
        echo "MongoDB Password: $MONGODB_PASSWORD"

    - name: Deploy Application
      run: |
        flask run  # Replace with actual deployment command
